module.exports = [
  {
    category_id: 34,
    image:
      '1665888548dorian-collet-potion-3d-dorian-collet-videogame-asset-props-0009-screenshot009.jpg',
    parent_id: 0,
    sort_order: 20,
    status: 1,
    category_description: {
      name: 'Potion',
      category_id: 34,
      description: null,
      meta_description: 'potion',
    },
  },
  {
    category_id: 36,
    image: '16666693285j3EyLQ2OFOt4f5xnYn0G8QaUyNx6SsvcqyooqQYUqU.webp',
    parent_id: 0,
    sort_order: 19,
    status: 1,
    category_description: {
      name: 'Herbs & Plants',
      category_id: 36,
      description: null,
      meta_description: 'Herbs & Plants',
    },
  },
  {
    category_id: 37,
    image: '1666665255anton-ruban-cg-art-fentezi-kniga.jpg',
    parent_id: 0,
    sort_order: 18,
    status: 1,
    category_description: {
      name: 'Books',
      category_id: 37,
      description: null,
      meta_description: 'books',
    },
  },
  {
    category_id: 29,
    image: '1665888785indigo.jpg',
    parent_id: 0,
    sort_order: 18,
    status: 1,
    category_description: {
      name: 'Resources',
      category_id: 29,
      description: null,
      meta_description: 'Resources',
    },
  },
  {
    category_id: 27,
    image: '1665934199istockphoto-151532403-612x612.jpg',
    parent_id: 0,
    sort_order: 17,
    status: 1,
    category_description: {
      name: 'Alloy',
      category_id: 27,
      description: null,
      meta_description: 'alloy',
    },
  },
  {
    category_id: 32,
    image: '1664522626osmium-crystals-992591878-5c4df53d46e0fb0001a8e7e4.jpg',
    parent_id: 0,
    sort_order: 17,
    status: 1,
    category_description: {
      name: 'Rocks & Minerals',
      category_id: 32,
      description: null,
      meta_description: 'Rocks & Minerals',
    },
  },
  {
    category_id: 33,
    image: '1665640651blackberries01.jpg',
    parent_id: 0,
    sort_order: 16,
    status: 1,
    category_description: {
      name: 'Food',
      category_id: 33,
      description: null,
      meta_description: 'food',
    },
  },
];
